#cloud-config
users:
  - name: neo
    lock_passwd: false
    passwd: 832627b4f6
    ssh_pwauth: true
package_upgrade: true
packages:
  - mongodb-server
write_files:
  - path: /etc/systemd/system/mongodb.service
    content: |
      [Unit]
      Description=MongoDB Database Service
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=mongod
      Group=mongod
      ExecStart=/usr/bin/mongod -f /etc/mongod.conf
      ExecReload=/bin/kill -HUP $MAINPID
      KillMode=process
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
runcmd:
  - systemctl daemon-reload
  - systemctl enable --now mongodb.service
  - sleep 10
  - mongo --eval 'db.names.insert({"name": "John Doe"})' demo
