# Use the official Python base image
FROM python:3.9

# Install curl, gnupg and netcat
RUN apt-get update && apt-get install -y curl gnupg netcat

# Add MongoDB public key and list file
RUN curl https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add -
RUN echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/6.0 main" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list

# Update the packages list
RUN apt-get update

# Install MongoDB shell
RUN apt-get install -y mongodb-mongosh

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY app.py .

# Expose the application port
EXPOSE 8080

# Run the application
CMD ["python", "app.py"]
