# Use the official Python base image
FROM registry.access.redhat.com/ubi8/python-39

# Install curl, gnupg and netcat
RUN yum -y update && yum -y install curl gnupg2 nmap-ncat

# Add MongoDB public key and list file
RUN curl https://www.mongodb.org/static/pgp/server-6.0.asc | gpg --import

# Create a repo file for MongoDB
RUN echo -e "[mongodb-org-6.0]\nname=MongoDB Repository\nbaseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/6.0/x86_64/\ngpgcheck=1\nenabled=1\ngpgkey=https://www.mongodb.org/static/pgp/server-6.0.asc" > /etc/yum.repos.d/mongodb-org-6.0.repo

# Install MongoDB shell
RUN yum -y install mongodb-org-shell

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY app.py .

# Expose the application port
EXPOSE 8080

# Run the application
CMD ["python", "app.py"]
