namespace: kubevirt-networking-poc-ns

app:
  image:
    repository: https://console-openshift-console.apps.sandbox-m2.ll9k.p1.openshiftapps.com/k8s/ns/dmorales-dev/imagestreamtags/kubevirt-networking-poc
    tag: latest
  service:
    type: LoadBalancer
    port: 8080

vm:
  imageName: kubevirt/fedora-cloud-container-disk-demo
  imageTag: v0.36.4
  cloudInitData: I2Nsb3VkLWNvbmZpZwpwYWNrYWdlX3VwZ3JhZGU6IHRydWUKcGFja2FnZXM6CiAgLSBtb25nb2RiCndyaXRlX2ZpbGVzOgogIC0gcGF0aDogL2V0Yy9tb25nb2QuY29uZgogICAgY29udGVudDogfAogICAgICBzdG9yYWdlOgogICAgICAgIGRiUGF0aDogL3Zhci9saWIvbW9uZ28KICAgICAgICBqb3VybmFsOgogICAgICAgICAgZW5hYmxlZDogdHJ1ZQogICAgICBzeXN0ZW1Mb2c6CiAgICAgICAgZGVzdGluYXRpb246IGZpbGUKICAgICAgICBsb2dBcHBlbmQ6IHRydWUKICAgICAgICBwYXRoOiAvdmFyL2xvZy9tb25nb2RiL21vbmdvZC5sb2cKICAgICAgbmV0OgogICAgICAgIHBvcnQ6IDI3MDE3CiAgICAgICAgYmluZElwOiAwLjAuMC4wCiAgLSBwYXRoOiAvcm9vdC9pbml0LW1vbmdvLmpzCiAgICBjb250ZW50OiB8CiAgICAgIGRiID0gbmV3IE1vbmdvKCkuZ2V0REIoImRlbW8iKTsKICAgICAgZGIubmFtZXMuaW5zZXJ0KHtuYW1lOiAiSm9obiBEb2UifSk7CnJ1bmNtZDoKICAtIHN5c3RlbWN0bCBlbmFibGUgbW9uZ29kCiAgLSBzeXN0ZW1jdGwgc3RhcnQgbW9uZ29kCiAgLSBzbGVlcCAxMAogIC0gbW9uZ28gPCAvcm9vdC9pbml0LW1vbmdvLmpzCgo=%

