namespace: kubevirt-networking-poc

app:
  image:
    repository: image-registry.openshift-image-registry.svc:5000/kubevirt-networking-poc/kubevirt-networking-poc
    tag: latest
  service:
    type: LoadBalancer
    port: 8080

vm:
  imageName: kubevirt/fedora-cloud-container-disk-demo
  imageTag: v0.36.4
  cloudInitData: I2Nsb3VkLWNvbmZpZwp1c2VyczoKICAtIGRlZmF1bHQKICAtIG5hbWU6IG5lbwogICAgcGxhaW5fdGV4dF9wYXNzd2Q6ICduZW8nCiAgICBsb2NrX3Bhc3N3ZDogZmFsc2UKICAtIG5hbWU6IGZlZG9yYQogICAgbG9ja19wYXNzd2Q6IGZhbHNlCiAgICBwbGFpbl90ZXh0X3Bhc3N3ZDogJ25lbycKcGFja2FnZV91cGdyYWRlOiB0cnVlCnBhY2thZ2VzOgogIC0gbW9uZ29kYi1zZXJ2ZXIKd3JpdGVfZmlsZXM6CiAgLSBwYXRoOiAvZXRjL3N5c3RlbWQvc3lzdGVtL21vbmdvZGIuc2VydmljZQogICAgY29udGVudDogfAogICAgICBbVW5pdF0KICAgICAgRGVzY3JpcHRpb249TW9uZ29EQiBEYXRhYmFzZSBTZXJ2aWNlCiAgICAgIFdhbnRzPW5ldHdvcmstb25saW5lLnRhcmdldAogICAgICBBZnRlcj1uZXR3b3JrLW9ubGluZS50YXJnZXQKCiAgICAgIFtTZXJ2aWNlXQogICAgICBVc2VyPW1vbmdvZAogICAgICBHcm91cD1tb25nb2QKICAgICAgRXhlY1N0YXJ0PS91c3IvYmluL21vbmdvZCAtZiAvZXRjL21vbmdvZC5jb25mCiAgICAgIEV4ZWNSZWxvYWQ9L2Jpbi9raWxsIC1IVVAgJE1BSU5QSUQKICAgICAgS2lsbE1vZGU9cHJvY2VzcwogICAgICBSZXN0YXJ0PW9uLWZhaWx1cmUKCiAgICAgIFtJbnN0YWxsXQogICAgICBXYW50ZWRCeT1tdWx0aS11c2VyLnRhcmdldApydW5jbWQ6CiAgLSBzeXN0ZW1jdGwgZGFlbW9uLXJlbG9hZAogIC0gc3lzdGVtY3RsIGVuYWJsZSAtLW5vdyBtb25nb2RiLnNlcnZpY2UKICAtIHNsZWVwIDEwCiAgLSBtb25nbyAtLWV2YWwgJ2RiLm5hbWVzLmluc2VydCh7XCJuYW1lXCI6IFwiSm9obiBEb2VcIn0pJyBkZW1v%
