namespace: kubevirt-networking-poc

app:
  image:
    repository: default-route-openshift-image-registry.apps.ocp.example.com/kubevirt-networking-poc/kubevirt-networking-poc-is
    tag: latest
  service:
    type: LoadBalancer
    port: 8080

vm:
  imageName: kubevirt/fedora-cloud-container-disk-demo
  imageTag: v0.36.4