apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kubevirt-networking-poc-bc
  namespace: {{ .Values.namespace }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: kubevirt-networking-poc:latest
  source:
    git:
      ref: cert-manager
      uri: 'https://github.com/david-morales/kubevirt-networking-poc.git'
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:3.9-ubi8'
        namespace: openshift
      env: []
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange