{{- $root := . -}}
{{- range $i := until (int $root.Values.mongodb.replicas) }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb-{{ $i }}
  namespace: {{ $root.Values.namespace }}
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    kubevirt.io/domain: mongodb-vm
{{- end }}