{{- range $i := until (int .Values.mongodb.replicaCount) }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb-{{ $i }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    kubevirt.io/domain: mongodb-vm-{{ $i }}
{{- end }}
