apiVersion: v1
kind: Secret
metadata:
  name: mongodb-vm-userdata
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  userdata: |
    #cloud-config
    users:
      - name: neo
        plain_text_passwd: 'neo'
        lock_passwd: false
        groups: users, admin
        sudo: ALL=(ALL) NOPASSWD:ALL
    hostname: mongodb-vm
    package_upgrade: true
    write_files:
      - content: |
          - hosts: localhost
            vars:
              mongodb_package: mongodb-org
              mongodb_repository: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/6.0/x86_64/
              mongodb_enable_authentication: no
              mongodb_net_bindip: 0.0.0.0
              mongodb_net_tls:
                mode: requireTLS
                certificateKeyFile: /etc/ssl/mongodb.pem
                CAFile: /etc/ssl/ca.crt
              mongodb_replication:
                replSetName: rs0
            roles:
              - mongodb.community
            tasks:
              - name: Initiate MongoDB replica set
                command: >
                  mongosh --tls --tlsCAFile /etc/ssl/ca.crt --tlsCertificateKeyFile /etc/ssl/mongodb.pem --host mongodb-vm --port 27017
                  --eval 'rs.initiate({_id: "rs0", members: [{_id: 0, host: "mongodb-vm-{{ .Values.mongodb.master }}:27017"}]})'
                become: yes
                when: ansible_hostname == "mongodb-vm-{{ .Values.mongodb.master }}"
              - name: Add remaining VMs to MongoDB replica set
                loop: "{{ range(1, .Values.mongodb.replicas) }}"
                command: >
                  mongosh --tls --tlsCAFile /etc/ssl/ca.crt --tlsCertificateKeyFile /etc/ssl/mongodb.pem --host mongodb-vm --port 27017
                  --eval 'rs.add({_id: {{ loop.index }}, host: "mongodb-vm-{{ loop.index }}:27017"})'
                become: yes
                when: ansible_hostname == "mongodb-vm-{{ .Values.mongodb.master }}"
        path: /root/mongodb_replica_setup.yml
    ansible:
      playbook:
        - /root/mongodb_replica_setup.yml
      roles:
        - name: mongodb.community
        src: https://galaxy.ansible.com/mongodb/community
  runcmd:
    - mkdir -p /mnt/mongodb-cert-tls && mount /dev/$(lsblk --nodeps -no name,serial | grep SERIAL | cut -f1 -d' ') /mnt/mongodb-cert-tls
    - cp /mnt/mongodb-cert-tls/tls.crt /etc/ssl/tls.crt
    - cp /mnt/mongodb-cert-tls/tls.key /etc/ssl/tls.key
    - cp /mnt/mongodb-cert-tls/ca.crt /etc/ssl/ca.crt
    - cat /etc/ssl/tls.crt /etc/ssl/tls.key > /etc/ssl/mongodb.pem
