apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-cert
  namespace: {{ .Values.namespace }}
spec:
  commonName: mongodb.{{ .Values.namespace }}.svc
  dnsNames:
  - mongodb.{{ .Values.namespace }}.svc.cluster.local
  - mongodb-vm
  - mongodb-vm-0
  - mongodb-vm-1
  - mongodb-vm-2
  - mongodb
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  secretName: mongodb-cert-tls
