apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-ansible-playbook
  namespace: {{ .Values.namespace }}
data:
  ansible_playbook.yml: 
  ansible_playbook.yml:: {{ range .Files.Lines "ansible/mongo-ansible-playbook.yml" }}
    {{ . }}{{ end }}
