apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-ansible-vars
  namespace: {{ .Values.namespace }}
data:
  ansible_vars.yml: |
    ansible_python_interpreter: /usr/bin/python3
    config_port: 27017
    mongodb_repository: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/6.0/x86_64/
    bind_ip: 0.0.0.0
    authorization: disabled
    mongodb_use_tls: true
    mongodb_certificate_key_file: /etc/ssl/mongodb.pem
    mongodb_certificate_ca_file: /etc/ssl/ca.crt
    skip_restart: false
    replicaset_name: rsneo
    repl_set_name: '{{ "{{ replicaset_name }}" }}'
    replicaset: true
    master_host: mongodb-2.poc-certificates.svc.cluster.local
