{{- $root := . -}}
{{- range $i := until (int $root.Values.mongodb.replicas) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-{{ $i }}
  namespace: {{ $root.Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end }}