{{- range $i := until (int .Values.mongodb.replicaCount) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-{{ $i }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end }}
