apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: mongodb-vm
  namespace: {{ .Values.namespace }}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: mongodb-vm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: mongodb-data
              disk:
                bus: virtio
            - disk: {}
              name: secret-disk
              serial: SERIAL
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
        resources:
          requests:
            memory: 2Gi
            cpu: 1
      networks:
        - name: default
          pod: {}
      livenessProbe:
        exec:
          command:
          - mongosh --tls --tlsCAFile /etc/ssl/ca.crt --tlsCertificateKeyFile /etc/ssl/mongodb.pem --host mongodb-vm --port 27017
          - --eval
          - db.adminCommand('ping')
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        exec:
          command:
          - mongosh --tls --tlsCAFile /etc/ssl/ca.crt --tlsCertificateKeyFile /etc/ssl/mongodb.pem --host mongodb-vm --port 27017
          - --eval
          - db.adminCommand('ping')
      volumes:
        - name: containerdisk
          containerDisk:
            image: "{{ .Values.vm.imageName }}:{{ .Values.vm.imageTag }}"
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: mongodb-vm-userdata
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - secret:
            secretName: mongodb-cert-tls
          name: secret-disk