{{- range $i := until (int .Values.mongodb.replicaCount) }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: mongodb-vm-{{ $i }}
  namespace: {{ $.Values.namespace }}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: mongodb-vm
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            - disk:
                bus: virtio
              name: mongodb-data
            - disk:              
              serial: 2SERIALANSIBLEVARS
              name: ansible-vars-disk
            - disk:              
              serial: 3SERIALANSIBLEPLAYBK
              name: ansible-playbook-disk
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
        resources:
          requests:
            memory: 2Gi
            cpu: 1
      hostname: {{ $.Values.mongodb.hostname_prefix }}-{{ $i }}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: "quay.io/containerdisks/centos-stream:7"
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: mongodb-vm-userdata
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc-{{ $i }}
        - configMap:
            name: mongo-ansible-vars
          name: ansible-vars-disk
        - configMap:
            name: mongo-ansible-playbook
          name: ansible-playbook-disk
{{- end }}
