{{- range $i := until (int .Values.mongodb.replicaCount) }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: mongodb-vm-{{ $i }}
  namespace: {{ $.Values.namespace }}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: mongodb-vm-{{ $i }}
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: mongodb-data
              disk:
                bus: virtio
            - disk: {}
              name: secret-disk
              serial: SERIAL
            - name: ansible-vars-disk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
        filesystems:
          - name: ansible-vars-disk
            mountPath: /ansible_vars/
        resources:
          requests:
            memory: 2Gi
            cpu: 1
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: "quay.io/containerdisks/centos-stream:9"
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: mongodb-vm-userdata
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc-{{ $i }}
        - secret:
            secretName: mongodb-cert-tls
          name: secret-disk
        - name: ansible-vars
          configMap:
            name: mongo-ansible-vars
{{- end }}
