namespace: poc-certificates

app:
  image:
    repository: image-registry.openshift-image-registry.svc:5000/poc-certificates/poc-certificates
    tag: latest
  service:
    type: LoadBalancer
    port: 8080

vm:
  imageName: quay.io/containerdisks/centos-stream
  imageTag: 9

mongodb:
  version: 4.2
  hostname_prefix: mongodb-vm
  replicaset_name: rsneo
  replicaCount: 3
  port: 27017
  authorization: enabled
  mongodb_use_tls: false
  app_user_password: "KyooZnZ2VkJoU21uQ0FNTQ=="
  #specific_mongodb_version: 4.2.6-1.el8 not working
