namespace: poc-certificates

app:
  image:
    repository: image-registry.openshift-image-registry.svc:5000/poc-certificates/poc-certificates
    tag: latest
  service:
    type: LoadBalancer
    port: 8080

vm:
  imageName: quay.io/containerdisks/centos-stream
  imageTag: 9

mongodb:
  hostname_prefix: mongodb-vm
  replicaCount: 3
  port: 27017
  authorization: enabled
  mongodb_use_tls: false
  replicaset_name: rsneo
  db_path: /product/mongodb/data
  log_path: /product/mongodb/log/mongod.log
  version: 4.2
  #specific_mongodb_version: 4.2.6-1.el8 not working
