namespace: poc-certificates

app:
  image:
    repository: image-registry.openshift-image-registry.svc:5000/poc-certificates/poc-certificates
    tag: latest
  service:
    type: LoadBalancer
    port: 8080

vm:
  imageName: quay.io/containerdisks/centos-stream
  imageTag: 9

mongodb:
  replicas: 3
  master: 0
