- hosts: localhost
  pre_tasks:
    - name: Include Ansible vars
      include_vars:
        file: /mnt/ansible-vars/ansible_vars.yml
  roles:
    - community.mongodb.mongodb_repository
    - community.mongodb.mongodb_install
    - community.mongodb.mongodb_mongod
  post_tasks:
    - name: Install python-setuptools
      package:
        name: python-setuptools
        state: latest
        update_cache: yes
    - name: Install python-pip
      package:
        name: python-pip
        state: latest
    - name: Ensure pymongo is installed
      pip:
        name: pymongo>2.4.2
        state: present
    - name: Generate list of mongodb hosts and convert to csv string
      set_fact:
        mongodb_list: "{{ mongodb_list|default([]) + ['mongodb-' + (item|string) + '.' + namespace + '.svc.cluster.local:' + config_port] }}"
        mongodb_csv: "{{ (mongodb_list|default([]) + ['mongodb-' + (item|string) + '.' + namespace + '.svc.cluster.local:' + config_port])|join(',') }}"
      loop: "{{ range(0, replicaset_size)|list }}"
    - debug:
        var: mongodb_csv
    - name: Ensure replicaset exists
      community.mongodb.mongodb_replicaset:
        login_host: 'mongodb-0.{{ namespace }}.svc.cluster.local'
        login_port: '{{ config_port }}'
        ssl: true
        ssl_certfile: '{{ mongodb_certificate_key_file }}'
        ssl_ca_certs: '{{ mongodb_certificate_ca_file }}'
        replica_set: '{{ replicaset_name }}'    
        members: '{{  mongodb_csv  }}'  
        validate: no
      when: ansible_hostname is search("-0")               
    - name: Wait for the replicaset to stabilise
      community.mongodb.mongodb_status:
        login_host: 'mongodb-0.{{ namespace }}.svc.cluster.local'
        login_port: '{{ config_port }}'
        ssl: true
        ssl_certfile: '{{ mongodb_certificate_key_file }}'
        ssl_ca_certs: '{{ mongodb_certificate_ca_file  }}'
        replica_set: '{{ replicaset_name }}'    
        poll: 6
        interval: 10
        validate: minimal
      when: ansible_hostname is search("-0") 