apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-networking-poc-helm
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubevirt-networking-poc
  template:
    metadata:
      labels:
        app: kubevirt-networking-poc
    spec:
      containers:
        - name: kubevirt-networking-poc
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubevirt-networking-poc-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 8080
  selector:
    app: kubevirt-networking-poc

