apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kubevirt-networking-poc-bc
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'kubevirt-networking-poc:latest'
  source:
    git:
      uri: https://github.com/david-morales/kubevirt-networking-poc.git
    contextDir: /
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.9-ubi8'
    type: Source
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChange:
      lastTriggeredImageID: ""
  runPolicy: Serial
  nodeSelector: null
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
