apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongodb-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      kubevirt.io/domain: mongodb-vm
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 27017

