apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: mongodb-vm
  namespace: {{ .Values.namespace }}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: mongodb-vm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: mongodb-data
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
        resources:
          requests:
            memory: 2Gi
            cpu: 1
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: "{{ .Values.vm.imageName }}:{{ .Values.vm.imageTag }}"
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: neo
                  passwd: c2cc277bcc10888ecee90f0f09ee9666199c2699922efb41ea7e88067b2c075f3dd3fbf3cfe9d0ec6173668dd83c111342f91e941a2cadc46a3a814848aa9b05
                  lock_passwd: false
                - name: fedora
                  passwd: c2cc277bcc10888ecee90f0f09ee9666199c2699922efb41ea7e88067b2c075f3dd3fbf3cfe9d0ec6173668dd83c111342f91e941a2cadc46a3a814848aa9b05
                  lock_passwd: false
              package_upgrade: true
              packages:
                - mongodb-server
              write_files:
                - path: /etc/systemd/system/mongodb.service
                  content: |
                    [Unit]
                    Description=MongoDB Database Service
                    Wants=network-online.target
                    After=network-online.target

                    [Service]
                    User=mongod
                    Group=mongod
                    ExecStart=/usr/bin/mongod -f /etc/mongod.conf
                    ExecReload=/bin/kill -HUP $MAINPID
                    KillMode=process
                    Restart=on-failure

                    [Install]
                    WantedBy=multi-user.target
              runcmd:
                - systemctl daemon-reload
                - systemctl enable --now mongodb.service
                - sleep 10
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc


