apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: mongodb-vm
  namespace: {{ .Values.namespace }}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: mongodb-vm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: mongodb-data
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
        resources:
          requests:
            memory: 2Gi
            cpu: 1
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: "{{ .Values.vm.imageName }}:{{ .Values.vm.imageTag }}"
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: neo
                  plain_text_passwd: 'neo'
                  lock_passwd: false
              package_upgrade: true
              write_files:
                - path: /etc/yum.repos.d/mongodb-org.repo
                  content: |
                    [mongodb-org-5.0]
                    name=MongoDB Repository
                    baseurl=https://repo.mongodb.org/yum/redhat/8/mongodb-org/5.0/x86_64/
                    gpgcheck=1
                    enabled=1
                    gpgkey=https://www.mongodb.org/static/pgp/server-5.0.asc
                - path: /etc/systemd/system/mongod.service
                  content: |
                    [Unit]
                    Description=MongoDB Database Service
                    Wants=network-online.target
                    After=network-online.target

                    [Service]
                    User=mongod
                    Group=mongod
                    ExecStart=/usr/bin/mongod -f /etc/mongod.conf
                    ExecReload=/bin/kill -HUP $MAINPID
                    KillMode=process
                    Restart=on-failure

                    [Install]
                    WantedBy=multi-user.target
              packages:
                - platform-python
                - mongodb-org
              runcmd:
                - systemctl daemon-reload
                - systemctl enable --now mongod.service
                - sleep 10
                - mongo --eval 'db.names.insert({\"name\": \"John Doe\"})' demo
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc


