apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: mongodb-vm
  namespace: {{ .Values.namespace }}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: mongodb-vm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: mongodb-data
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
        resources:
          requests:
            memory: 2Gi
            cpu: 1
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: "{{ .Values.vm.imageName }}:{{ .Values.vm.imageTag }}"
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              package_upgrade: true

              packages:
                - epel-release
                - mongodb-server
                - mongodb
                - mongodb-tools

              write_files:
                - path: /etc/yum.repos.d/mongodb.repo
                  content: |
                    [mongodb-org-4.4]
                    name=MongoDB Repository
                    baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.4/x86_64/
                    gpgcheck=1
                    enabled=0
                    gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
                - path: /root/init-mongo.js
                  content: |
                    db = new Mongo().getDB("demo");
                    db.names.insert({name: "John Doe"});

              runcmd:
                - dnf -y --enablerepo=mongodb-org-4.4 install mongodb-org
                - systemctl daemon-reload
                - systemctl enable --now mongod.service
                - sleep 10
                - mongo < /root/init-mongo.js
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
